name: Download data

on:
  # Activate while pushing to master
  push:
    branches:
    - master
  # Activate UTC 17:30 everyday
  # ref: crontab.guru
  schedule:
  - cron: 30 17 * * *

jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run main
      run:
        python main.py
